services:
  mongo:
    image: mongo:8
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--username",
          "${MONGO_ROOT_USERNAME}",
          "--password",
          "${MONGO_ROOT_PASSWORD}",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    environment:
      PYTHONPATH: /app/src
      MONGO_HOST: mongo

    ports:
    - "8000:8000"

    volumes:
      - ./cost_logs:/app/cost_logs

    depends_on:
      mongo:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


volumes:
  mongo_data:
