REFUND_WINDOW_DAYS = 30
REFUND_AUTO_APPROVAL_LIMIT = 200.00

REPLACEMENT_WINDOW_DAYS = 30
REPLACEMENT_AUTO_APPROVAL_LIMIT = 300.00

CANCELLATION_AUTO_APPROVAL_LIMIT = 500.00

TRIAGE_MIN_CONFIDENCE = 0.60

RESOLUTION_MIN_CONFIDENCE = 0.65

HIGH_RISK_LEVEL = "high"
MEDIUM_RISK_LEVEL = "medium"
RESTRICTED_ACCOUNT_STATUS = "restricted"